HelpInfo,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\bin\mbin\assistant
Implementation;Synthesis;RootName:Zhq
Implementation;Synthesis||null||@N: Running in 64-bit mode||Zhq.srr(11);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/11||null;null
Implementation;Synthesis||null||@N: Running in 64-bit mode||Zhq.srr(15);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/15||null;null
Implementation;Synthesis|| CG364 ||@N: Synthesizing module W_zh5 in library work.||Zhq.srr(30);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/30||W_zh4.v(2);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\hdl\W_zh4.v'/linenumber/2
Implementation;Synthesis|| CG364 ||@N: Synthesizing module Zhq in library work.||Zhq.srr(32);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/32||Zhq.v(9);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\component\work\Zhq\Zhq.v'/linenumber/9
Implementation;Synthesis||null||@N: Running in 64-bit mode||Zhq.srr(44);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/44||null;null
Implementation;Synthesis|| MF248 ||@N: Running in 64-bit mode.||Zhq.srr(86);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/86||null;null
Implementation;Synthesis|| MF667 ||@N: Clock conversion disabled. (Command "set_option -fix_gated_and_generated_clocks 0" in the project file.)||Zhq.srr(87);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/87||null;null
Implementation;Synthesis|| BN225 ||@N: Writing default property annotation file G:\EDA\W_zh5\synthesis\Zhq.sap.||Zhq.srr(108);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/108||null;null
Implementation;Synthesis|| MF248 ||@N: Running in 64-bit mode.||Zhq.srr(135);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/135||null;null
Implementation;Synthesis|| MF667 ||@N: Clock conversion disabled. (Command "set_option -fix_gated_and_generated_clocks 0" in the project file.)||Zhq.srr(136);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/136||null;null
Implementation;Synthesis|| MF236 ||@N: Generating a type div divider ||Zhq.srr(151);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/151||w_zh4.v(13);liberoaction://cross_probe/hdl/file/'g:\eda\w_zh5\hdl\w_zh4.v'/linenumber/13
Implementation;Synthesis|| MF237 ||@N: Generating a type rem remainder ||Zhq.srr(152);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/152||w_zh4.v(14);liberoaction://cross_probe/hdl/file/'g:\eda\w_zh5\hdl\w_zh4.v'/linenumber/14
Implementation;Synthesis|| MF236 ||@N: Generating a type div divider ||Zhq.srr(153);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/153||w_zh4.v(12);liberoaction://cross_probe/hdl/file/'g:\eda\w_zh5\hdl\w_zh4.v'/linenumber/12
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(157);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/157||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(158);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/158||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(159);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/159||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(160);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/160||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(161);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/161||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(162);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/162||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(163);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/163||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(164);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/164||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(165);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/165||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(166);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/166||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(167);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/167||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(168);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/168||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(169);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/169||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(170);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/170||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(171);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/171||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(172);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/172||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(173);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/173||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(174);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/174||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(175);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/175||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(176);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/176||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(177);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/177||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(178);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/178||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(179);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/179||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(180);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/180||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(181);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/181||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(182);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/182||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(183);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/183||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(184);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/184||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(185);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/185||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(186);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/186||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(187);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/187||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(188);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/188||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(189);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/189||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(190);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/190||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(191);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/191||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(192);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/192||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(193);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/193||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(194);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/194||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(195);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/195||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(196);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/196||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(197);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/197||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(198);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/198||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(199);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/199||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(200);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/200||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(201);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/201||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(202);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/202||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||Zhq.srr(203);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/203||null;null
Implementation;Synthesis|| MT320 ||@N: This timing report is an estimate of place and route data. For final timing results, use the FPGA vendor place and route report.||Zhq.srr(291);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/291||null;null
Implementation;Synthesis|| MT322 ||@N: Clock constraints include only register-to-register paths associated with each individual clock.||Zhq.srr(293);liberoaction://cross_probe/hdl/file/'G:\EDA\W_zh5\synthesis\Zhq.srr'/linenumber/293||null;null
Implementation;Compile;RootName:Zhq
Implementation;Compile||(null)||Please refer to the log file for details||Zhq_compile_log.rpt;liberoaction://open_report/file/Zhq_compile_log.rpt||(null);(null)
