Implementation;Generate Bitstream;RootName:W_74HC138
HelpInfo,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\bin\mbin\assistant
Implementation;Compile;RootName:W_74HC138
Implementation;Compile||(null)||Please refer to the log file for details about 1 Info(s)||W_74HC138_compile_log.rpt;liberoaction://open_report/file/W_74HC138_compile_log.rpt||(null);(null)
Implementation;Place and Route;RootName:W_74HC138
Implementation;Place and Route||(null)||Please refer to the log file for details about 1 Info(s)||W_74HC138_placeroute_log.rpt;liberoaction://open_report/file/W_74HC138_placeroute_log.rpt||(null);(null)
