HelpInfo,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\bin\mbin\assistant
Implementation;Synthesis;RootName:Ymtz
Implementation;Synthesis||null||@N: Running in 64-bit mode||Ymtz.srr(11);liberoaction://cross_probe/hdl/file/'C:\EDA\W_zh2\synthesis\Ymtz.srr'/linenumber/11||null;null
Implementation;Synthesis||null||@N: Running in 64-bit mode||Ymtz.srr(15);liberoaction://cross_probe/hdl/file/'C:\EDA\W_zh2\synthesis\Ymtz.srr'/linenumber/15||null;null
Implementation;Synthesis|| CG364 ||@N: Synthesizing module W_74HC138 in library work.||Ymtz.srr(31);liberoaction://cross_probe/hdl/file/'C:\EDA\W_zh2\synthesis\Ymtz.srr'/linenumber/31||74HC138.v(2);liberoaction://cross_probe/hdl/file/'C:\EDA\W_zh2\hdl\74HC138.v'/linenumber/2
Implementation;Synthesis|| CG364 ||@N: Synthesizing module W_74HC4511 in library work.||Ymtz.srr(33);liberoaction://cross_probe/hdl/file/'C:\EDA\W_zh2\synthesis\Ymtz.srr'/linenumber/33||74HC4511.v(2);liberoaction://cross_probe/hdl/file/'C:\EDA\W_zh2\hdl\74HC4511.v'/linenumber/2
Implementation;Synthesis|| CG364 ||@N: Synthesizing module Ymtz in library work.||Ymtz.srr(35);liberoaction://cross_probe/hdl/file/'C:\EDA\W_zh2\synthesis\Ymtz.srr'/linenumber/35||Ymtz.v(9);liberoaction://cross_probe/hdl/file/'C:\EDA\W_zh2\component\work\Ymtz\Ymtz.v'/linenumber/9
Implementation;Synthesis||null||@N: Running in 64-bit mode||Ymtz.srr(47);liberoaction://cross_probe/hdl/file/'C:\EDA\W_zh2\synthesis\Ymtz.srr'/linenumber/47||null;null
Implementation;Synthesis|| MF248 ||@N: Running in 64-bit mode.||Ymtz.srr(89);liberoaction://cross_probe/hdl/file/'C:\EDA\W_zh2\synthesis\Ymtz.srr'/linenumber/89||null;null
Implementation;Synthesis|| MF667 ||@N: Clock conversion disabled. (Command "set_option -fix_gated_and_generated_clocks 0" in the project file.)||Ymtz.srr(90);liberoaction://cross_probe/hdl/file/'C:\EDA\W_zh2\synthesis\Ymtz.srr'/linenumber/90||null;null
Implementation;Synthesis|| BN225 ||@N: Writing default property annotation file C:\EDA\W_zh2\synthesis\Ymtz.sap.||Ymtz.srr(111);liberoaction://cross_probe/hdl/file/'C:\EDA\W_zh2\synthesis\Ymtz.srr'/linenumber/111||null;null
Implementation;Synthesis|| MF248 ||@N: Running in 64-bit mode.||Ymtz.srr(138);liberoaction://cross_probe/hdl/file/'C:\EDA\W_zh2\synthesis\Ymtz.srr'/linenumber/138||null;null
Implementation;Synthesis|| MF667 ||@N: Clock conversion disabled. (Command "set_option -fix_gated_and_generated_clocks 0" in the project file.)||Ymtz.srr(139);liberoaction://cross_probe/hdl/file/'C:\EDA\W_zh2\synthesis\Ymtz.srr'/linenumber/139||null;null
Implementation;Synthesis|| MT320 ||@N: This timing report is an estimate of place and route data. For final timing results, use the FPGA vendor place and route report.||Ymtz.srr(244);liberoaction://cross_probe/hdl/file/'C:\EDA\W_zh2\synthesis\Ymtz.srr'/linenumber/244||null;null
Implementation;Synthesis|| MT322 ||@N: Clock constraints include only register-to-register paths associated with each individual clock.||Ymtz.srr(246);liberoaction://cross_probe/hdl/file/'C:\EDA\W_zh2\synthesis\Ymtz.srr'/linenumber/246||null;null
Implementation;Compile;RootName:Ymtz
Implementation;Compile||(null)||Please refer to the log file for details||Ymtz_compile_log.rpt;liberoaction://open_report/file/Ymtz_compile_log.rpt||(null);(null)
