Implementation;Generate Bitstream;RootName:W_74HC148
HelpInfo,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\bin\mbin\assistant
Implementation;Synthesis;RootName:W_74HC148
Implementation;Synthesis||null||@N: Running in 64-bit mode||W_74HC148.srr(11);liberoaction://cross_probe/hdl/file/'I:\EDA\zuhe\W_74HC148\synthesis\W_74HC148.srr'/linenumber/11||null;null
Implementation;Synthesis||null||@N: Running in 64-bit mode||W_74HC148.srr(15);liberoaction://cross_probe/hdl/file/'I:\EDA\zuhe\W_74HC148\synthesis\W_74HC148.srr'/linenumber/15||null;null
Implementation;Synthesis|| CG364 ||@N: Synthesizing module W_74HC148 in library work.||W_74HC148.srr(27);liberoaction://cross_probe/hdl/file/'I:\EDA\zuhe\W_74HC148\synthesis\W_74HC148.srr'/linenumber/27||W_74HC148.v(1);liberoaction://cross_probe/hdl/file/'I:\EDA\zuhe\W_74HC148\hdl\W_74HC148.v'/linenumber/1
Implementation;Synthesis||null||@N: Running in 64-bit mode||W_74HC148.srr(39);liberoaction://cross_probe/hdl/file/'I:\EDA\zuhe\W_74HC148\synthesis\W_74HC148.srr'/linenumber/39||null;null
Implementation;Synthesis||null||@N: Running in 64-bit mode||W_74HC148.srr(61);liberoaction://cross_probe/hdl/file/'I:\EDA\zuhe\W_74HC148\synthesis\W_74HC148.srr'/linenumber/61||null;null
Implementation;Synthesis|| MF248 ||@N: Running in 64-bit mode.||W_74HC148.srr(85);liberoaction://cross_probe/hdl/file/'I:\EDA\zuhe\W_74HC148\synthesis\W_74HC148.srr'/linenumber/85||null;null
Implementation;Synthesis|| MF667 ||@N: Clock conversion disabled. (Command "set_option -fix_gated_and_generated_clocks 0" in the project file.)||W_74HC148.srr(86);liberoaction://cross_probe/hdl/file/'I:\EDA\zuhe\W_74HC148\synthesis\W_74HC148.srr'/linenumber/86||null;null
Implementation;Synthesis|| BN225 ||@N: Writing default property annotation file I:\EDA\zuhe\W_74HC148\synthesis\W_74HC148.sap.||W_74HC148.srr(107);liberoaction://cross_probe/hdl/file/'I:\EDA\zuhe\W_74HC148\synthesis\W_74HC148.srr'/linenumber/107||null;null
Implementation;Synthesis|| MF248 ||@N: Running in 64-bit mode.||W_74HC148.srr(134);liberoaction://cross_probe/hdl/file/'I:\EDA\zuhe\W_74HC148\synthesis\W_74HC148.srr'/linenumber/134||null;null
Implementation;Synthesis|| MF667 ||@N: Clock conversion disabled. (Command "set_option -fix_gated_and_generated_clocks 0" in the project file.)||W_74HC148.srr(135);liberoaction://cross_probe/hdl/file/'I:\EDA\zuhe\W_74HC148\synthesis\W_74HC148.srr'/linenumber/135||null;null
Implementation;Synthesis|| MT320 ||@N: This timing report is an estimate of place and route data. For final timing results, use the FPGA vendor place and route report.||W_74HC148.srr(240);liberoaction://cross_probe/hdl/file/'I:\EDA\zuhe\W_74HC148\synthesis\W_74HC148.srr'/linenumber/240||null;null
Implementation;Synthesis|| MT322 ||@N: Clock constraints include only register-to-register paths associated with each individual clock.||W_74HC148.srr(242);liberoaction://cross_probe/hdl/file/'I:\EDA\zuhe\W_74HC148\synthesis\W_74HC148.srr'/linenumber/242||null;null
Implementation;Compile;RootName:W_74HC148
Implementation;Compile||(null)||Please refer to the log file for details about 1 Info(s)||W_74HC148_compile_log.rpt;liberoaction://open_report/file/W_74HC148_compile_log.rpt||(null);(null)
