HelpInfo,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\bin\mbin\assistant
Implementation;Synthesis;RootName:W_74HC283
Implementation;Synthesis||null||@N: Running in 64-bit mode||W_74HC283.srr(11);liberoaction://cross_probe/hdl/file/'C:\EDA\W_74HC283\synthesis\W_74HC283.srr'/linenumber/11||null;null
Implementation;Synthesis||null||@N: Running in 64-bit mode||W_74HC283.srr(15);liberoaction://cross_probe/hdl/file/'C:\EDA\W_74HC283\synthesis\W_74HC283.srr'/linenumber/15||null;null
Implementation;Synthesis|| CG364 ||@N: Synthesizing module W_74HC283 in library work.||W_74HC283.srr(27);liberoaction://cross_probe/hdl/file/'C:\EDA\W_74HC283\synthesis\W_74HC283.srr'/linenumber/27||W_74HC283.v(2);liberoaction://cross_probe/hdl/file/'C:\EDA\W_74HC283\hdl\W_74HC283.v'/linenumber/2
Implementation;Synthesis||null||@N: Running in 64-bit mode||W_74HC283.srr(39);liberoaction://cross_probe/hdl/file/'C:\EDA\W_74HC283\synthesis\W_74HC283.srr'/linenumber/39||null;null
Implementation;Synthesis||null||@N: Running in 64-bit mode||W_74HC283.srr(61);liberoaction://cross_probe/hdl/file/'C:\EDA\W_74HC283\synthesis\W_74HC283.srr'/linenumber/61||null;null
Implementation;Synthesis|| MF248 ||@N: Running in 64-bit mode.||W_74HC283.srr(85);liberoaction://cross_probe/hdl/file/'C:\EDA\W_74HC283\synthesis\W_74HC283.srr'/linenumber/85||null;null
Implementation;Synthesis|| MF667 ||@N: Clock conversion disabled. (Command "set_option -fix_gated_and_generated_clocks 0" in the project file.)||W_74HC283.srr(86);liberoaction://cross_probe/hdl/file/'C:\EDA\W_74HC283\synthesis\W_74HC283.srr'/linenumber/86||null;null
Implementation;Synthesis|| BN225 ||@N: Writing default property annotation file C:\EDA\W_74HC283\synthesis\W_74HC283.sap.||W_74HC283.srr(107);liberoaction://cross_probe/hdl/file/'C:\EDA\W_74HC283\synthesis\W_74HC283.srr'/linenumber/107||null;null
Implementation;Synthesis|| MF248 ||@N: Running in 64-bit mode.||W_74HC283.srr(134);liberoaction://cross_probe/hdl/file/'C:\EDA\W_74HC283\synthesis\W_74HC283.srr'/linenumber/134||null;null
Implementation;Synthesis|| MF667 ||@N: Clock conversion disabled. (Command "set_option -fix_gated_and_generated_clocks 0" in the project file.)||W_74HC283.srr(135);liberoaction://cross_probe/hdl/file/'C:\EDA\W_74HC283\synthesis\W_74HC283.srr'/linenumber/135||null;null
Implementation;Synthesis|| MF176 ||@N: Default generator successful ||W_74HC283.srr(153);liberoaction://cross_probe/hdl/file/'C:\EDA\W_74HC283\synthesis\W_74HC283.srr'/linenumber/153||null;null
Implementation;Synthesis|| MT320 ||@N: This timing report is an estimate of place and route data. For final timing results, use the FPGA vendor place and route report.||W_74HC283.srr(241);liberoaction://cross_probe/hdl/file/'C:\EDA\W_74HC283\synthesis\W_74HC283.srr'/linenumber/241||null;null
Implementation;Synthesis|| MT322 ||@N: Clock constraints include only register-to-register paths associated with each individual clock.||W_74HC283.srr(243);liberoaction://cross_probe/hdl/file/'C:\EDA\W_74HC283\synthesis\W_74HC283.srr'/linenumber/243||null;null
Implementation;Compile;RootName:W_74HC283
Implementation;Compile||(null)||Please refer to the log file for details||W_74HC283_compile_log.rpt;liberoaction://open_report/file/W_74HC283_compile_log.rpt||(null);(null)
